# Generated by Django 6.0.6 on 2026-07-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='player_picture/')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('pace', models.SmallIntegerField(default=50)),
                ('shooting', models.SmallIntegerField(default=50)),
                ('passing', models.SmallIntegerField(default=50)),
                ('dribbling', models.SmallIntegerField(default=50)),
                ('physicality', models.SmallIntegerField(default=50)),
                ('defending', models.SmallIntegerField(default=50)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MD', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('preferred_foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Right', max_length=100)),
                ('age', models.SmallIntegerField(default=18)),
                ('shirt_number', models.SmallIntegerField(default=1)),
                ('height', models.SmallIntegerField(default=180)),
                ('weight', models.SmallIntegerField(default=75)),
                ('nationality', models.CharField(max_length=100)),
                ('market_value', models.PositiveIntegerField(default=0)),
                ('joined', models.DateField()),
                ('contract_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('season', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('name', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_card', models.PositiveIntegerField(default=0)),
                ('red_card', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('short_name', models.CharField(help_text='e.g Ars,MCI', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='footballapp.league')),
                ('trophy', models.ManyToManyField(blank=True, related_name='team', to='footballapp.trophy')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='footballapp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='footballapp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='footballapp.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='trophy',
            field=models.ManyToManyField(blank=True, related_name='player', to='footballapp.trophy'),
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('win', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('loss', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.team')),
            ],
            options={
                'unique_together': {('team', 'league')},
            },
        ),
    ]
