# Generated by Django 6.0.7 on 2026-07-31 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transfer_type', models.CharField(choices=[('Free', 'Free'), ('Loan', 'Loan'), ('Permanent', 'Permanent')], max_length=120)),
                ('transfer_status', models.CharField(choices=[('Rumour', 'Rumour'), ('FreeAgent', 'FreeAgent'), ('Loan', 'Loan'), ('OfficIal', 'OfficIal')], max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footballapp.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.player')),
                ('team_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_out', to='footballapp.team')),
                ('team_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in', to='footballapp.team')),
            ],
        ),
    ]
